on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verify git repository
        uses: actions/checkout@v2

      - name: Install node with the version
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install dependecies
        run: npm install

      - name: Verify lint errors
        run: npx eslint .

  Evaluator:
    runs-on: ubuntu-latest
    needs: [eslint]

    steps:
      - name: Install dependÃªncies
        uses: actions/checkout@v1
        run: npm install
      - name: Starting tests
        run: npm test